### ISSUE TITLE
TH2016 Redux: Content Checklist

### ISSUE THREAD

**Issue by caseyg** [caseyg/tomhealy#23]
- [ ] Hi-res official author photo of Tom (to offer as a download)
- [ ] Two photographs of each of Tom's books on a white background, facing forward, but showing the physicality/depth.
- [ ] A lead sentence for each book, shorter and punchier than the paragraph-long descriptions that’re there now. (This is the first thing you see on the page, and we will move the description lower.)
- [ ] New photograph for the homepage (you’ll be able to change this whenever)
- [ ] Combined list of book/poetry reviews of Tom's Work and interviews with Tom, which will be moved to the About page. (Currently they are buried in an "Interviews" page at the bottom of the About page, and also in subpages of each book.)
- [ ] Short bio
- [ ] Long bio
- [ ] One image for each event, if it exists (if not that's okay, but we will make this section a little more visual!)
- [ ] One sentence explaining some of the most-used/non-obvious taxonomy pages, e.g. what is the collection of Fulbright about?
- [ ] Non-corny collage of Tom images for About page? Farm? Slides?
- [ ] Animal Spirits Duke Riley illustrations (we will scatter these around the Animal Spirits page)
- [ ] Any more book excerpts that haven't been posted?
- [ ] Any free-floating poems that aren’t attached to a book, can be a link offsite if you don't have publishing rights
